JPosting.UI/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JPosting.DATA.EF;
using Microsoft.AspNet.Identity;

namespace JPosting.UI.Controllers
{
    
    public class ApplicationsController : Controller
    {
        private FinalProjectEntities db = new FinalProjectEntities();

        // GET: Applications
        public ActionResult Index()
        {
            if (User.IsInRole("Admin"))
            {
                var applications = db.Applications.Include(a => a.AspNetUsers).Include(a => a.OpenPositions);
                return View(applications.ToList());
            }
            else if (User.IsInRole("Manager"))
            {
                //list of applications in the location of that current user
                //where ManagerID for that loaction == userID
                var currentUser = User.Identity.GetUserId();
                var applications = db.Applications.Where(x => x.OpenPositions.Locations.ManagerID == currentUser).ToList();
                return View(applications);
            }
            else
            {
                //current employee's where the app is not declined
                //employees
                //list where UserID == UserID(aspnet.identity)
                var currentUser = User.Identity.GetUserId();
                var application = db.Applications.Where(x => x.UserID == currentUser).ToList();
                return View(application.Where(x => x.IsDeclined == false));
            }
        }

        // GET: Applications/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applications applications = db.Applications.Find(id);
            if (applications == null)
            {
                return HttpNotFound();
            }
            return View(applications);
        }

        // GET: Applications/Create
        public ActionResult Create()
        {
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.OpenPositionID = new SelectList(db.OpenPositions, "OpenPositionsID", "OpenPositionsID");
            return View();
        }
        // Get
        public ActionResult Apply(int id)
        {
            Applications app = new Applications();
            app.OpenPositionID = id;
            app.ApplicationDate = DateTime.Now;
            app.UserID = User.Identity.GetUserId();
            app.IsDeclined = false;
            return View(app);
        }

        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Apply(Applications app,HttpPostedFileBase resumeUpload)
        {
            Applications application = new Applications();
            application.ApplicationDate = DateTime.Now;
            application.UserID = User.Identity.GetUserId();
            application.ResumeFilename = resumeUpload.FileName;
            application.IsDeclined = false;
            application.OpenPositionID = app.OpenPositionID;

            //if (ModelState.IsValid)
            //{
                #region File Upload

                //check and see if there was a file uploaded, if not, default to the noimage.jpg
                string file = "noResume.pdf";

                //if a file has been uploaded
                if (resumeUpload != null)
                {
                    //get the name
                    file = resumeUpload.FileName;

                    //get the extension
                    string ext = file.Substring(file.LastIndexOf('.')).ToLower();

                    //check extension against a list of "good" extensions
                    string goodExt = ".pdf";

                    //see if this file is a pdf
                    if (ext == goodExt)
                    {
                        //this is a valid photo

                        Session["SizeError"] = null;
                        //create a new file name using a quid()
                        //file = Guid.NewGuid() + ext;

                        //create a unique name for each resume upload
                        file = application.UserID + DateTime.Now.Year + ext;

                        //save file to server
                        resumeUpload.SaveAs((Server.MapPath("~/Content/Images/" + file)));


                    }//if contains extension

                    //no matter what happens we need to update that photo Url property of the new student  in the DB
                    application.ResumeFilename = file;

                }//end if student photo not null

                #endregion

                db.Applications.Add(application);
                db.SaveChanges();
                return RedirectToAction("Index");
            //}

            //return View(application);
        }

        // POST: Applications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ApplicationID,OpenPositionID,UserID,ApplicationDate,ManagerNotes,IsDeclined,ResumeFilename")] Applications applications, HttpPostedFileBase resumeUpload)
        {
            if (ModelState.IsValid)
            {
                #region File Upload

                //check and see if there was a file uploaded, if not, default to the noimage.jpg
                string file = "noResume.pdf";

                //if a file has been uploaded
                if (resumeUpload != null)
                {
                    //get the name
                    file = resumeUpload.FileName;

                    //get the extension
                    string ext = file.Substring(file.LastIndexOf('.')).ToLower();

                    //check extension against a list of "good" extensions
                    string goodExt = ".pdf";

                    //see if this file is a photo
                    if (ext == goodExt)
                    {
                        //this is a valid photo
                      
                            Session["SizeError"] = null;
                            //create a new file name using a quid()
                            //file = Guid.NewGuid() + ext;

                            //create a unique name for each resume upload
                            file = applications.UserID + DateTime.Now.Year + ext;

                            //save file to server
                            resumeUpload.SaveAs((Server.MapPath("~/Content/Images/" + file)));
                       

                    }//if contains extension

                    //no matter what happens we need to update that photo Url property of the new student  in the DB
                    applications.ResumeFilename = file;

                }//end if student photo not null

                #endregion

                db.Applications.Add(applications);
                db.SaveChanges();
                return View(applications);
            }

            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", applications.UserID);
            ViewBag.OpenPositionID = new SelectList(db.OpenPositions, "OpenPositionsID", "OpenPositionsID", applications.OpenPositionID);
            return View(applications);
        }

        // GET: Applications/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applications applications = db.Applications.Find(id);
            if (applications == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", applications.UserID);
            ViewBag.OpenPositionID = new SelectList(db.OpenPositions, "OpenPositionsID", "OpenPositionsID", applications.OpenPositionID);
            return View(applications);
        }

        // POST: Applications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ApplicationID,OpenPositionID,UserID,ApplicationDate,ManagerNotes,IsDeclined,ResumeFilename")] Applications applications)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applications).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", applications.UserID);
            ViewBag.OpenPositionID = new SelectList(db.OpenPositions, "OpenPositionsID", "OpenPositionsID", applications.OpenPositionID);
            return View(applications);
        }

        // GET: Applications/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applications applications = db.Applications.Find(id);
            if (applications == null)
            {
                return HttpNotFound();
            }
            return View(applications);
        }

        // POST: Applications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Applications applications = db.Applications.Find(id);
            db.Applications.Remove(applications);
            db.SaveChanges();

JPosting.UI/Views/Applications/Apply.cshtml
@model JPosting.DATA.EF.Applications

@{
    ViewBag.Title = "Apply";
}

<h2>Apply</h2>


@using (Html.BeginForm("Apply", "Applications", FormMethod.Post, new { @enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Applications</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
     @Html.HiddenFor(x=> x.OpenPositionID)
        @Html.HiddenFor(x => x.ApplicationDate)
        @Html.HiddenFor(x => x.IsDeclined)

        <div class="form-group">
            @Html.LabelFor(model => model.ResumeFilename, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <strong>Upload Resume: </strong><input type="file" name="resumeUpload" />
                @*@Html.EditorFor(model => model.ResumeFilename, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResumeFilename, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Apply" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JPosting.UI/Views/Applications/Create.cshtml
@model JPosting.DATA.EF.Applications

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Applications", FormMethod.Post, new { @enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Applications</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.OpenPositionID, "OpenPositionID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OpenPositionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OpenPositionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManagerNotes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ManagerNotes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManagerNotes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDeclined, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDeclined)
                    @Html.ValidationMessageFor(model => model.IsDeclined, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResumeFilename, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                <strong>Upload Resume: </strong><input type="file" name="resumeUpload" />
                @*@Html.EditorFor(model => model.ResumeFilename, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResumeFilename, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JPosting.UI/Views/Applications/Delete.cshtml
@model JPosting.DATA.EF.Applications

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Applications</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManagerNotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManagerNotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeclined)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeclined)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResumeFilename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResumeFilename)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUsers.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUsers.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpenPositions.OpenPositionsID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpenPositions.OpenPositionsID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JPosting.UI/Views/Applications/Details.cshtml
@model JPosting.DATA.EF.Applications

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Applications</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManagerNotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManagerNotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeclined)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeclined)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResumeFilename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResumeFilename)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUsers.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUsers.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpenPositions.OpenPositionsID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpenPositions.OpenPositionsID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ApplicationID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

JPosting.UI/Views/Applications/Edit.cshtml
@model JPosting.DATA.EF.Applications

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Applications</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ApplicationID)

        <div class="form-group">
            @Html.LabelFor(model => model.OpenPositionID, "OpenPositionID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OpenPositionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OpenPositionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManagerNotes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ManagerNotes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManagerNotes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            &nbsp;&nbsp;&nbsp; Hire
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDeclined)
                    @Html.ValidationMessageFor(model => model.IsDeclined, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResumeFilename, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResumeFilename, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResumeFilename, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JPosting.UI/Views/Applications/Index.cshtml
@model IEnumerable<JPosting.DATA.EF.Applications>

@{
    ViewBag.Title = "Applications";
}

<h2>@ViewBag.Title</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationDate)
        </th>
        @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
        {
            <th>
                @Html.DisplayNameFor(model => model.ManagerNotes)
            </th>
        }

        <th>
            @Html.DisplayNameFor(model => model.IsDeclined)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ResumeFilename)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.AspNetUsers.Email)
            </th>*@
        @*<th>
            @Html.DisplayNameFor(model => model.OpenPositions.OpenPositionsID)
        </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationDate)
            </td>
            @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
            {
                <td>
                    @Html.DisplayFor(modelItem => item.ManagerNotes)
                </td>
            }

            <td>
                 Under Review
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.ResumeFilename)*@
                <a href="~/Content/Images/@item.ResumeFilename" target="_blank" class="btn btn-info">View Resume</a>
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.AspNetUsers.Email)
                </td>*@
            @*<td>
                @Html.DisplayFor(modelItem => item.OpenPositions.OpenPositionsID)
            </td>*@
            <td>
                @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.ApplicationID }, new { @class = "btn btn-primary" })
                }
                @Html.ActionLink("Delete", "Delete", new { id = item.ApplicationID }, new { @class = "btn btn-danger" })
                @*@Html.ActionLink("Details", "Details", new { id = item.ApplicationID }) |*@

            </td>
        </tr>
    }

</table>