JPosting.UI/Controllers/OpenPositionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JPosting.DATA.EF;
using Microsoft.AspNet.Identity;

namespace JPosting.UI.Controllers
{
    public class OpenPositionsController : Controller
    {
        private FinalProjectEntities db = new FinalProjectEntities();

        // GET: OpenPositions
        public ActionResult Index()
        {
            if (User.IsInRole("Manager"))
            {
                //lock down so manager role can only see open positions at there location
                var currentUserId = User.Identity.GetUserId();
                var position = db.OpenPositions.Include(i => i.Locations).Where(x => x.Locations.ManagerID == currentUserId).ToList();
                return View(position);
            }
            else
            {
                //employees and admin can see all open positions
                
                var openPositions = db.OpenPositions.Include(o => o.Locations).Include(o => o.Positions);
                return View(openPositions.ToList());
            }
        }

        // GET: OpenPositions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPositions openPositions = db.OpenPositions.Find(id);
            if (openPositions == null)
            {
                return HttpNotFound();
            }
            return View(openPositions);
        }

        // GET: OpenPositions/Create
        public ActionResult Create()
        {
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "StoreNumber");
            ViewBag.PositionID = new SelectList(db.Positions, "PositionID", "Title");
            return View();
        }

        // POST: OpenPositions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OpenPositionsID,PositionID,LocationID")] OpenPositions openPositions)
        {
            if (ModelState.IsValid)
            {
                db.OpenPositions.Add(openPositions);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "StoreNumber", openPositions.LocationID);
            ViewBag.PositionID = new SelectList(db.Positions, "PositionID", "Title", openPositions.PositionID);
            return View(openPositions);
        }

        // GET: OpenPositions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPositions openPositions = db.OpenPositions.Find(id);
            if (openPositions == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "StoreNumber", openPositions.LocationID);
            ViewBag.PositionID = new SelectList(db.Positions, "PositionID", "Title", openPositions.PositionID);
            return View(openPositions);
        }

        // POST: OpenPositions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OpenPositionsID,PositionID,LocationID")] OpenPositions openPositions)
        {
            if (ModelState.IsValid)
            {
                db.Entry(openPositions).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "StoreNumber", openPositions.LocationID);
            ViewBag.PositionID = new SelectList(db.Positions, "PositionID", "Title", openPositions.PositionID);
            return View(openPositions);
        }

        // GET: OpenPositions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPositions openPositions = db.OpenPositions.Find(id);
            if (openPositions == null)
            {
                return HttpNotFound();
            }
            return View(openPositions);
        }

        // POST: OpenPositions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OpenPositions openPositions = db.OpenPositions.Find(id);
            db.OpenPositions.Remove(openPositions);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JPosting.UI/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <title>Papa Hutinoes</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", false)
    <!-- Main CSS -->
    @*<link rel="stylesheet" href="css/style.css">*@
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet"/>
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Sofia" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>

<body>
    <!-- Header -->
    <div class="header-wrap d-none d-md-block" id="homeBanner">
        <div class="container">
            <div class="row" >

                <!-- Left header box -->
                <header class="col-12 text-right">
                    <h3>Papa Hutinoes</h3>
                </header>

                <!-- Right header box -->
                @*<div class="col-6 text-right">
                    <p class="header-social-icons social-icons">
                        <a href="#"><i class="fa fa-facebook fa-2x"></i></a>
                        <a href="#"><i class="fa fa-twitter fa-2x"></i></a>
                        <a href="#"><i class="fa fa-youtube fa-2x"></i></a>
                        <a href="#"><i class="fa fa-instagram fa-2x"></i></a>
                    </p>
                </div>*@
            </div>
        </div>
    </div>

    <!-- Main navigation -->
    <nav class="navbar navbar-expand-md navbar-dark bg-primary">
        <div class="container">

            <!-- Company name shown on mobile -->
            <a class="navbar-brand d-md-none d-lg-none d-xl-none" href="#">Papa Hutinoes</a>
            <!-- Mobile menu toggle -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNavbar" aria-controls="mainNavbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Main navigation items -->
            <div class="collapse navbar-collapse" id="mainNavbar">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        
                    </li>

                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin Tools</a>
                            <div class="dropdown-menu navbar-dark bg-primary">
                                @Html.ActionLink("RolesAdmin", "Index", "RolesAdmin", null, new { @class = "nav-link" })
                                @Html.ActionLink("UsersAdmin", "Index", "UsersAdmin", null, new { @class = "nav-link" })
                                @Html.ActionLink("Positions", "Index", "Positions", null, new { @class = "nav-link" })
                                
                            </div>
                        </li>
                    }
                    

                    <li class="nav-item">
                        @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Locations", "Index", "Locations", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Applications", "Index", "Applications", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                       @Html.ActionLink("Open Positions", "Index", "OpenPositions", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link" })
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>

            <!-- Main navigation items -->

            @*<div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <ul class="navbar-collapse collapse nav navbar-nav">

                <li>@Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })</li>
                @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                @*<li>@Html.ActionLink("Positions", "Index", "Positions")</li>*@
                @*<li>@Html.ActionLink("Locations", "Index", "Locations", null, new { @class = "nav-link" })</li>
                <li>@Html.ActionLink("Applications", "Index", "Applications", null, new { @class = "nav-link" })</li>
                <li>@Html.ActionLink("Open Positions", "Index", "OpenPositions", null, new { @class = "nav-link" })</li>
                @if (User.IsInRole("Admin"))
                {
                    <li>
                        <a href="javascript:void(0)" class="dropBtnA">Administrative Tools</a>
                        <ul class="dropAreaA hide">
                            <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin", null, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin", null, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Positions", "Index", "Positions", null, new { @class = "nav-link" })</li>
                        </ul>
                    </li>
                }





            </ul>*@

        </div>
    </nav>

    <!-- Jumbtron / Slider -->
    <!-- Main content area -->
    <main class="container">
        @RenderBody()
    </main>

    <!-- Footer -->
    <footer>
        <p class="footer">&copy; @DateTime.Now.Year - Papa Hutinoes</p>
    </footer>

    <!-- Bootcamp JavaScript -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript">
        $(function () {
            $('.dropBtnA').click(function () {
                $('.dropAreaA').toggleClass('hide');
            });
            $("#accordion").accordion({
                collapsible: true
            });
        });

    </script>
      @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
   
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    @*<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

</body>
</html>

JPosting.UI/Views/Shared/_OriginalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <ul class="navbar-collapse collapse nav navbar-nav">

                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                @*<li>@Html.ActionLink("Positions", "Index", "Positions")</li>*@
                <li>@Html.ActionLink("Locations", "Index", "Locations")</li>
                <li>@Html.ActionLink("Applications", "Index", "Applications")</li>
                <li>@Html.ActionLink("Open Positions", "Index", "OpenPositions")</li>
                @if (User.IsInRole("Admin"))
                {
                    <li>
                        <a href="javascript:void(0)" class="dropBtnA">Administrative Tools</a>
                        <ul class="dropAreaA hide">
                            <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                            <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                            <li>@Html.ActionLink("Positions", "Index", "Positions")</li>
                        </ul>
                    </li>
                }





            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('.dropBtnA').click(function () {
                $('.dropAreaA').toggleClass('hide');
            });

        });

    </script>
</body>
</html>